NAME				=	loggator
BINARY_NAME			=	loggator
LIBRARY_NAME		=	loggator.a
BINARY_DIRECTORY	=	./bin/
LIBRARY_DIRECTORY	=	./lib/
SOURCE_DIRECTORY	=	./src/
TEST_DIRECTORY		=	./test/
INCLUDE_DIRECTORY	=	../../include/ ./include/
OBJECT_DIRECTORY	=	./obj/
SOURCE_EXTENTION	=	.cpp

LIBRARY_EXCLUDE_SOURCE = main.cpp

COMPILER			=	g++
COMMON_FLAGS		=	-std=c++11
DEBUG_FLAGS			=	-ggdb -Wall -Wextra
RELEASE_FLAGS		=	-O2 -Wall -Wextra -Werror
TEST_FLAGS			=	-std=c++11 -ggdb -Wall -Wextra

# local libraries (example: -lpthread)
DEBUG_LIBRARIES		=	
RELEASE_LIBRARIES	=	
TEST_LIBRARIES		=	

include ../../templateMakefile/module.mk