NAME				=	test
BINARY_NAME			=	test
LIBRARY_NAME		=	test.a
BINARY_DIRECTORY	=	./bin/
LIBRARY_DIRECTORY	=	
SOURCE_DIRECTORY	=	./src/
INCLUDE_DIRECTORY	=	../../include/ ./include/
OBJECT_DIRECTORY	=	./obj/

COMPILER			=	g++
COMMON_FLAGS		=	-std=c++11
DEBUG_FLAGS			=	-ggdb -Wall -Wextra
RELEASE_FLAGS		=	-O2 -Wall -Wextra -Werror
TEST_FLAGS			=	

# local libraries (example: -lpthread)
DEBUG_LIBRARIES		=	
RELEASE_LIBRARIES	=	
TEST_LIBRARIES		=	

include ../../templateMakefile/module.mk