##
## Author: Mickaël BLET
##

VERSION						=	0.0.0

DEFAULT_NAME				=	$(notdir $(CURDIR))
DEFAULT_BINARY_NAME			=	$(DEFAULT_NAME)
DEFAULT_LIBRARY_NAME		=	$(addsuffix .a, $(DEFAULT_NAME))
DEFAULT_BINARY_DIRECTORY	=	bin/
DEFAULT_LIBRARY_DIRECTORY	=	lib/
DEFAULT_SOURCE_DIRECTORY	=	src/
DEFAULT_INCLUDE_DIRECTORY	=	include/
DEFAULT_OBJECT_DIRECTORY	=	obj/

DEFAULT_COMPILER			=	$(CC)
DEFAULT_COMMON_FLAGS		=	$(CFLAGS)
DEFAULT_DEBUG_FLAGS			=
DEFAULT_RELEASE_FLAGS		=
DEFAULT_TEST_FLAGS			=

DEFAULT_DEBUG_LIBRARIES		=
DEFAULT_RELEASE_LIBRARIES	=
DEFAULT_TEST_LIBRARIES		=	-lgtest -lgtest_main -lgmock -lpthread

#------------------------------------------------------------------------------
# Can be modified out template

NAME				:=	$(if $(strip $(NAME)),$(NAME),$(DEFAULT_NAME))
BINARY_NAME			:=	$(if $(strip $(BINARY_NAME)),$(BINARY_NAME),$(DEFAULT_BINARY_NAME))
LIBRARY_NAME		:=	$(if $(strip $(LIBRARY_NAME)),$(LIBRARY_NAME),$(DEFAULT_LIBRARY_NAME))
BINARY_DIRECTORY	:=	$(if $(strip $(BINARY_DIRECTORY)),$(BINARY_DIRECTORY),$(DEFAULT_BINARY_DIRECTORY))
LIBRARY_DIRECTORY	:=	$(if $(strip $(LIBRARY_DIRECTORY)),$(LIBRARY_DIRECTORY),$(DEFAULT_LIBRARY_DIRECTORY))
SOURCE_DIRECTORY	:=	$(if $(strip $(SOURCE_DIRECTORY)),$(SOURCE_DIRECTORY),$(DEFAULT_SOURCE_DIRECTORY))
INCLUDE_DIRECTORY	:=	$(if $(strip $(INCLUDE_DIRECTORY)),$(INCLUDE_DIRECTORY),$(DEFAULT_INCLUDE_DIRECTORY))
OBJECT_DIRECTORY	:=	$(if $(strip $(OBJECT_DIRECTORY)),$(OBJECT_DIRECTORY),$(DEFAULT_OBJECT_DIRECTORY))

COMPILER			:=	$(if $(strip $(COMPILER)),$(COMPILER),$(DEFAULT_COMPILER))
COMMON_FLAGS		:=	$(if $(strip $(COMMON_FLAGS)),$(COMMON_FLAGS),$(DEFAULT_COMMON_FLAGS))
DEBUG_FLAGS			:=	$(if $(strip $(DEBUG_FLAGS)),$(DEBUG_FLAGS),$(DEFAULT_DEBUG_FLAGS))
RELEASE_FLAGS		:=	$(if $(strip $(RELEASE_FLAGS)),$(RELEASE_FLAGS),$(DEFAULT_RELEASE_FLAGS))
TEST_FLAGS			:=	$(if $(strip $(TEST_FLAGS)),$(TEST_FLAGS),$(DEFAULT_TEST_FLAGS))

# local libraries (example: -lpthread)
DEBUG_LIBRARIES		:=	$(if $(strip $(DEBUG_LIBRARIES)),$(DEBUG_LIBRARIES),$(DEFAULT_DEBUG_LIBRARIES))
RELEASE_LIBRARIES	:=	$(if $(strip $(RELEASE_LIBRARIES)),$(RELEASE_LIBRARIES),$(DEFAULT_RELEASE_LIBRARIES))
TEST_LIBRARIES		:=	$(if $(strip $(TEST_LIBRARIES)),$(TEST_LIBRARIES),$(DEFAULT_TEST_LIBRARIES))

#------------------------------------------------------------------------------

FIND_SOURCE				=	$(shell find $(SOURCE_DIRECTORY) -name "*.cpp")
SOURCE					:=	$(subst $(SOURCE_DIRECTORY),,$(FIND_SOURCE))
OBJECT_DEBUG			:=	$(addprefix $(OBJECT_DIRECTORY),$(SOURCE:.cpp=_debug-$(VERSION).o))
INCLUDE_PATH			:=	$(addprefix -I, $(INCLUDE_DIRECTORY))

#------------------------------------------------------------------------------

all:	debug

test:
	echo $(SOURCE) $(SOURCE_DIRECTORY) $(OBJECT_DEBUG)

$(BINARY_DIRECTORY) $(LIBRARY_DIRECTORY):
	@mkdir -p $(sort $(dir $@))

$(OBJECT_DEBUG_DIRECTORY):
	@mkdir -p $(sort $(dir $(OBJECT_DEBUG)))

$(OBJECT_DIRECTORY)%_debug-$(VERSION).o:	$(SOURCE_DIRECTORY)%.cpp | $(OBJECT_DEBUG_DIRECTORY)
	$(COMPILER) $(COMMON_FLAGS) $(DEBUG_FLAGS) -MMD -c $< -o $@ $(INCLUDE_PATH)

$(OBJECT_RELEASE_DIRECTORY)%.o:	$(SOURCE_DIRECTORY)%.cpp | $(OBJECT_RELEASE_DIRECTORY)
	$(COMPILER) $(COMMON_FLAGS) $(RELEASE_FLAGS) -MMD -c $< -o $@ $(INCLUDE_PATH)

$(BINARY_DIRECTORY)$(BINARY_NAME): $(OBJECT_DEBUG)
	$(COMPILER) $(COMMON_FLAGS) $(DEBUG_FLAGS) -o $@ $^ $(INCLUDE_PATH)

debug:	$(BINARY_DIRECTORY)$(BINARY_NAME) | $(BINARY_DIRECTORY)

clean:
	$(RM) $(OBJECT_DEBUG) $(OBJECT_DEBUG:.o=.d)

re:		clean
	$(MAKE) all

#------------------------------------------------------------------------------

-include $(OBJECT_DEBUG:.o=.d)
-include $(OBJECT_RELEASE:.o=.d)
-include $(OBJECT_TEST:.o=.d)